eureka:
  client:
    register-with-eureka: false
  instance:
    hostname: localhost
feign:
  hystrix:
    enabled: true
server:
  port: 8222
spring:
  application:
    name: gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

      routes:
        - id: orders
          uri: lb://orders
          predicates:
            - Path=/api/v1/orders/**
          filters:
            - AuthenticationFilter

        - id: payments
          uri: lb://payments
          predicates:
            - Path=/api/v1/payments/**
          filters:
            - AuthenticationFilter

        - id: restaurants
          uri: lb://restaurants
          predicates:
            - Path=/api/v1/restaurants/**
          filters:
            - AuthenticationFilter

        - id: reviews
          uri: lb://reviews
          predicates:
            - Path=/api/v1/reviews/**
          filters:
            - AuthenticationFilter

        - id: users
          uri: lb://users
          predicates:
            - Path=/auth/**
          filters:
            - AuthenticationFilter

        - id: products
          uri: lb://restaurants
          predicates:
            - Path=/api/v1/products/**
          filters:
            - AuthenticationFilter

application:
  config:
    auth-users-url: http://localhost:8076/auth
