eureka:
  client:
    register-with-eureka: false
server:
  port: 8222
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      mvc:
        routes:
          - id: order
            uri: http://localhost:8071
            predicates:
              - Path=/api/v1/order/**
          - id: payment
            uri: http://localhost:8072
            predicates:
              - Path=/api/v1/payments/**
          - id: restaurant
            uri: http://localhost:8070
            predicates:
              - Path=/api/v1/restaurants/**
          - id: orders
            uri: http://localhost:8073
            predicates:
              - Path=/api/v1/reviews/**
