server:
  port: 8888
spring:
  profiles:
    active: native
  application:
    name: config-server
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configurations #artik configurationlari bu path ten cekecek
          #yml dosyasinin ismi ile mikroservis altindaki yml daki proje isminin ayni olmasi lazim
